
name: Run CASR
on:
  push:

jobs:
  run-casr:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} Run CASR

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 0194926b3bcf70cc0d7bfd3c5da16708dd5ab876
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Compile using gradle
      run: |
        ./gradlew clean build -x test
    - name: Install rust and dependencies
      run: | 
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y        
        sudo apt install gdb lsb-release
    - name: Install casr
      run: |
        cargo install casr
    - name: Run CASR
      run: |
        find . -name '*.java' -exec sh -c 'echo "Processing {}" && timeout 60s casr-java -o {}.casrep -- java  {}' \;
    - name: List any casr reports created
      run: |
        find . -type f -name "*.casrep"
